FROM jetbrains/teamcity-agent:2021.2.3-linux-sudo

USER root

RUN apt-get update

RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | tee /etc/apt/sources.list.d/microsoft.list

RUN apt-get update
RUN apt-get install -y powershell
RUN apt-get install -y apt-transport-https
RUN apt-get update
RUN apt-get install -y dotnet-sdk-6.0

RUN curl -sL https://deb.nodesource.com/setup_lts.x | sudo -E bash -

RUN apt-get install -y nodejs
RUN apt-get install -y build-essential

USER buildagent