version: '3'

services:
  teamcity:
    restart: unless-stopped
    image: jetbrains/teamcity-server:2021.2.1
    container_name: teamcity-server
    environment:
      - TEAMCITY_HTTPS_PROXY_ENABLED=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./files/server/data:/data/teamcity_server/datadir
      - ./files/server/logs:/opt/teamcity/logs
    ports:
      - 8111:8111

  agent:
    restart: unless-stopped
    build: 
      context: .
      dockerfile: dockerfile-agent
    environment:
      - SERVER_URL=http://teamcity:8111
      - DOCKER_IN_DOCKER=start
    privileged: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - teamcity

  postgres:
    container_name: teamcity-postgres
    image: postgres:14.1
    restart: unless-stopped
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "postgres"

  pgadmin:
    container_name: teamcity-pgadmin
    image: dpage/pgadmin4:6.3
    restart: unless-stopped
    tty: true
    ports:
      - "5480:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@postgres.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    depends_on:
      - postgres
