version: '3'

services:
  teamcity:
    image: jetbrains/teamcity-server
    container_name: teamcity-server
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./files/server/data:/data/teamcity_server/datadir
      - ./files/server/logs:/opt/teamcity/logs
    ports:
      - 8111:8111

  agent:
    restart: unless-stopped
    build: 
      context: .
      dockerfile: dockerfile-agent
    environment:
      - SERVER_URL=http://teamcity:8111
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - teamcity
